### ISSUE TITLE
git clone https://github.com/ipdk-io/p4-ovs

### ISSUE THREAD

**Issue by AmitDavidi** [ipdk-io/ovs#93]
this link does not exist, did you mean git clone https://github.com/ipdk-io/ovs ?
in the installation 
https://github.com/ipdk-io/ovs/blob/ovs-with-p4/Documentation/intro/install/ovs-with-p4-general.rst

**Comment by ffoulkes** [comment]
The `ovs-with-p4` branch is obsolete. It was for an older version of the software.

**P4-OVS** was the pilot version of the software. It integrated OVS, Stratum, and a several other packages into a single monolithic application.

The pilot version was superseded by a disaggregated package called **P4-OVS Split Architecture** (to begin with), and then **IPDK Networking Recipe** or **P4 Control Plane**.

P4 Control Plane consists of a number of repositories, all on <https://github.com/ipdk-io>:

- [networking-recipe](https://github.com/ipdk-io/networking-recipe) is the superproject. It contains ovs, stratum, and a number of other repositories as submodules. The active branch is `main`.
- [ovs](https://github.com/ipdk-io/ovs) is a modified fork of <https://github.com/openvswitch/ovs>. The active branch is `idpk-latest`.
- [krnlmon](https://github.com/ipdk-io/krnlmon) is a heavily modified version of <https://github.com/p4lang/switch>. The active branch is `main`.
- [stratum-dev](https://github.com/ipdk-io/stratum-dev) is a heavily modified fork of <https://github.com/stratum/stratum>. The active branch is `split-arch`.
- [p4runtime-dev](https://github.com/ipdk-io/p4runtime-dev) is a modified fork of <https://github.com/p4lang/p4runtime>. The active branch is `meters`.

As well as:

- [p4cp-userguide](https://github.com/ipdk-io/p4cp-userguide) is the source for the user guide.
- [stratum-deps](https://github.com/ipdk-io/stratum-deps) downloads and builds the Stratum dependencies.

There's a more detailed [Overview](https://ipdk.io/p4cp-userguide/overview/overview.html) of the components in the P4 Control Plane User Guide.

See <https://github.com/ipdk-io/networking-recipe> for more information.

I hope this helps.

**Comment by ffoulkes** [comment]
The issue is with an old branch that is no longer under development. I have provided an explanation and information on the current branch(es) in an earlier comment.

See the [user guide](https://ipdk.io/p4cp-userguide/) for the superproject that superseded P4-OVS for more current information.

We have not made any additions to the OVS documentation in the current branch.

**Comment by ffoulkes** [comment]
The issue is with an old branch that is no longer under development. I have provided an explanation and information on the current branch(es) in an earlier comment.

See the [user guide](https://ipdk.io/p4cp-userguide/) for the superproject that superseded P4-OVS for more current information.

We have not made any additions to the OVS documentation in the current branch.
